name: animated_line_through
description: Animated line through for text for Flutter, with full control over animation
version: 1.0.2
homepage: https://github.com/Vorkytaka/animated_line_through
repository: https://github.com/Vorkytaka/animated_line_through
issue_tracker: https://github.com/Vorkytaka/animated_line_through/issues

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
